version: "3"
services:
  wantedlab_app:
    container_name: wantedlab_app
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    restart: always
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app/
    environment:
      - TZ="Asia/Seoul"
